# Generated by Django 5.2.8 on 2026-04-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=255)),
                ('matricula', models.CharField(max_length=50, unique=True)),
                ('data_nascimento', models.DateField()),
                ('curso', models.CharField(max_length=100)),
                ('turma', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='estudantes_fotos/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
