# Generated by Django 5.2.8 on 2026-04-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_estudante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudante',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
    ]
