# Generated by Django 5.2.8 on 2026-04-15 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_digital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='senha',
        ),
    ]
