# Generated by Django 5.2.8 on 2026-04-22 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_usuario_senha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('cafe', 'Café'), ('almoco', 'Almoço'), ('jantar', 'Jantar')], max_length=20)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes', to='api.estudante')),
            ],
        ),
    ]
